//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shared.resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shared.resource.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionError.
        /// </summary>
        internal static string Connection_Error {
            get {
                return ResourceManager.GetString("Connection Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefectiveEntry.
        /// </summary>
        internal static string Defective_Entry {
            get {
                return ResourceManager.GetString("Defective Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceIdNotFound.
        /// </summary>
        internal static string DeviceId_Not_Found {
            get {
                return ResourceManager.GetString("DeviceId Not Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyId.
        /// </summary>
        internal static string Empty_Id {
            get {
                return ResourceManager.GetString("Empty Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalServerError.
        /// </summary>
        internal static string Internal_Server_Error {
            get {
                return ResourceManager.GetString("Internal Server Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signin attempt.
        /// </summary>
        internal static string Invalid_signin_attempt {
            get {
                return ResourceManager.GetString("Invalid signin attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NothingFound.
        /// </summary>
        internal static string Nothing_Found {
            get {
                return ResourceManager.GetString("Nothing Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneIsNotVerified.
        /// </summary>
        internal static string Phone_Is_Not_Verified {
            get {
                return ResourceManager.GetString("Phone Is Not Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetrieveLimit.
        /// </summary>
        internal static string Retrieve_Limit {
            get {
                return ResourceManager.GetString("Retrieve Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenNotFound.
        /// </summary>
        internal static string Token_Not_Found {
            get {
                return ResourceManager.GetString("Token Not Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedError.
        /// </summary>
        internal static string Unexpected_Error {
            get {
                return ResourceManager.GetString("Unexpected Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIsNotActive.
        /// </summary>
        internal static string User_Is_Not_Active {
            get {
                return ResourceManager.GetString("User Is Not Active", resourceCulture);
            }
        }
    }
}
